### ISSUE TITLE
Client类get方法的query参数换成options

### ISSUE THREAD

**Issue by AilonHuang** [overtrue/http#23]
Client类get方法的query参数换成options，之前调用是直接在第二个参数写query数组，现在版本更新后需要把所有get方法的第二个参数更改为['query' => [...]]，请问有什么方法可以快速更新代码

**Comment by overtrue** [comment]
Sorry，实在抱歉，刚才翻阅了一下更新历史，确实是在 1.1.3 发布的时候改错了（也不知道当时处于什么考量），按理讲这种破坏性变更应该发布 2.0 才对的（可能是发版的时候忘记了有破坏性变更）。

如果调用处不多，麻烦就辛苦逐个改一下吧。多的话，考虑用正则批量替换一下（风险较高）。
