### ISSUE TITLE
1.1.3 版本里面存在的 postJson 方法，在 1.2.0, 1.1.4, 1.1.5 里面居然就被删除了

### ISSUE THREAD

**Issue by zhouyl** [overtrue/http#24]
做为开源软件应该要严谨，在跨小版本迭代时，不应该直接删除提供的方法，而是应该在 phpdoc 里打上 @deprecated  标识，并说明将在哪个版本中完全移除。

**Comment by overtrue** [comment]
https://github.com/overtrue/http/issues/23
