### ISSUE TITLE
三元表达式的问题

### ISSUE THREAD

**Issue by imjcw** [overtrue/http#31]
若 `is_resource` 结果是 `true`，那么 `$contents` 就是 `true` ？

应该是 ` $contents = \is_resource($contents) ? $contents : \fopen($contents, 'r');` 吧？

https://github.com/overtrue/http/blob/40009b5fa69268ddcbb7fd5c6f63b17fe731c4b5/src/Client.php#L237

**Comment by overtrue** [comment]
你说的对，PR 一下？
