### ISSUE TITLE
Overtrue\Http\Support\Collection 不支持php8

### ISSUE THREAD

**Issue by bkkkd** [overtrue/http#34]
Overtrue\Http\Support\Collection 不支持php8
__set_state(),offsetGet,offsetSet和offsetUnset实现不兼容
Serializable 未实现

**Comment by overtrue** [comment]
@bkkkd 欢迎试用：

```php
composer require overtrue/http:dev-master
```

**Comment by bkkkd** [comment]
还是不行.看了大部分#[ReturnTypeWillChange] 来兼容php7和php8
