### ISSUE TITLE
请教一下，为什么删除之前的postJson 方法呢？

### ISSUE THREAD

**Issue by over-star** [overtrue/http#36]

**Comment by overtrue** [comment]
其实当时看没几个人用，star 数就不到100，看了一下下载量应该就我自己用，所以就大重构了一版，有不少破坏性变更，postJson 主要是考虑它其实不是一个标准一些的方法，如果加上的话， getJson, patchJson, deleteJson 都要加，就感觉必要性不大，当然如果你觉得必要性有的话我也可以全部加上哈。
